name: Checkout Test

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Before checkout"

      - uses: actions/checkout@v4

      - run: echo "After checkout"
